apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: momo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/erkules/momo.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-momo
  namespace: flux-system
spec:
  path: .
  sourceRef:
    kind: GitRepository
    name: momo
  interval: 1m
  prune:    true

